# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

# Window Rules
windowrule=tags:8,appid:discord,isopensilent:1,istagsilent:1
windowrule=tags:1,title:Godot Nvim,isopensilent:1,istagsilent:1

windowrule=isglobal:1,isfloating:1,width:1200,height:900,title:LibrePods

windowrule=isglobal:1,isfloating:1,offsetx:100,offsety:88,width:800,height:450,title:Picture-in-Picture
windowrule=isfloating:1,isopensilent:1,offsetx:100,offsety:88,width:600,height:600,appid:octave-gui
windowrule=isfloating:1,isopensilent:1,offsetx:100,offsety:83,width:600,height:600,appid:Gnuplot
windowrule=isfloating:1,isopensilent:1,offsetx:100,offsety:83,width:600,height:600,appid:Matplotlib
windowrule=isfloating:1,isopensilent:1,offsetx:100,offsety:83,width:600,height:600,appid:python3

# windowrule=isglobal:1,isfloating:1,width:1200,height:900,title:calc
# windowrule=isglobal:1,isfloating:1,width:1200,height:900,title:term
# windowrule=isglobal:1,isfloating:1,width:1200,height:900,title:audiomix
# windowrule=isglobal:1,isfloating:1,width:1700,height:1200,title:bluetooth

windowrule=isglobal:1,isfloating:1,width:900,height:600,appid:com.floating.small
windowrule=isglobal:1,isfloating:1,width:1200,height:900,appid:com.floating.normal
windowrule=isglobal:1,isfloating:1,width:1700,height:1200,appid:com.floating.big

# Monitor Rules
# name,mfact,nmaster,layout,transform,scale,x,y,width,height,refreshrate
monitorrule=name:eDP-1,0.55,1,tile,0,1,0,0,2256,1504,60
monitorrule=name:DP-4,0.55,1,tile,0,1,2256,0,2560,1440,164.8
